GRANT ALL ON kodilla_tester TO "kodilla_user";

SELECT *
FROM USERS U
JOIN POSTS P ON U.ID = P.USER_ID;

INSERT INTO POSTS(ID,USER_ID,BODY) VALUES (9,1,"The weather is killing me.");
INSERT INTO POSTS(ID,USER_ID,BODY) VALUES (10,3,"Yeah. I hate Novembers!");
INSERT INTO POSTS(ID,USER_ID,BODY) VALUES (11,3,"Can't wait until Christmas.");
INSERT INTO POSTS(ID,USER_ID,BODY) VALUES (12,1, "Me neither!");
INSERT INTO POSTS(ID,USER_ID,BODY) VALUES (13,4, "I already made cookies.");
INSERT INTO POSTS(ID,USER_ID,BODY) VALUES (14,4, "They are delicious.");
COMMIT;

INSERT INTO POSTS(ID,USER_ID,BODY) VALUES (20,2,'I burned my cookies.');
INSERT INTO POSTS(ID,USER_ID,BODY) VALUES (21,2,'Now shops are closed and I cannot buy any.');
INSERT INTO POSTS(ID,USER_ID,BODY) VALUES (22,2,'Shame.');
COMMIT;

SELECT U.FIRSTNAME, U.LASTNAME
FROM USERS U
JOIN POSTS P ON U.ID = P.USER_ID
GROUP BY U.LASTNAME
HAVING COUNT(P.BODY) > 2;

SELECT COUNT(DISTINCT U.ID) 
FROM USERS U 
JOIN POSTS P ON U.ID = P.USER_ID
HAVING COUNT(P.BODY) > 2;

DELETE FROM POSTS
WHERE ID = 20;
DELETE FROM POSTS
WHERE ID = 21;
DELETE FROM POSTS
WHERE ID = 22;
COMMIT;

